
package webWsdl.te;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TellTimeService", targetNamespace = "http://sp/", wsdlLocation = "http://localhost/8005/tell?wsdl")
public class TellTimeService
    extends Service
{

    private final static URL TELLTIMESERVICE_WSDL_LOCATION;
    private final static WebServiceException TELLTIMESERVICE_EXCEPTION;
    private final static QName TELLTIMESERVICE_QNAME = new QName("http://sp/", "TellTimeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/8005/tell?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TELLTIMESERVICE_WSDL_LOCATION = url;
        TELLTIMESERVICE_EXCEPTION = e;
    }

    public TellTimeService() {
        super(__getWsdlLocation(), TELLTIMESERVICE_QNAME);
    }

    public TellTimeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TELLTIMESERVICE_QNAME, features);
    }

    public TellTimeService(URL wsdlLocation) {
        super(wsdlLocation, TELLTIMESERVICE_QNAME);
    }

    public TellTimeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TELLTIMESERVICE_QNAME, features);
    }

    public TellTimeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TellTimeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TellTime
     */
    @WebEndpoint(name = "TellTimePort")
    public TellTime getTellTimePort() {
        return super.getPort(new QName("http://sp/", "TellTimePort"), TellTime.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TellTime
     */
    @WebEndpoint(name = "TellTimePort")
    public TellTime getTellTimePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sp/", "TellTimePort"), TellTime.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TELLTIMESERVICE_EXCEPTION!= null) {
            throw TELLTIMESERVICE_EXCEPTION;
        }
        return TELLTIMESERVICE_WSDL_LOCATION;
    }

}
