
package webWsdl.te;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TellTime", targetNamespace = "http://sp/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TellTime {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "printTime", targetNamespace = "http://sp/", className = "webWsdl.te.PrintTime")
    @ResponseWrapper(localName = "printTimeResponse", targetNamespace = "http://sp/", className = "webWsdl.te.PrintTimeResponse")
    @Action(input = "http://sp/TellTime/printTimeRequest", output = "http://sp/TellTime/printTimeResponse")
    public void printTime();

}
